paths:
  raw_data: "data/raw/SMSSpamCollection.txt"
  processed_data: "data/processed/sms_clean.csv"
  model: "models/spam_classifier_v2.pkl"

model:
  max_features_words: 5000
  max_features_chars: 3000
  ngram_range_words: [1, 3]
  ngram_range_chars: [2, 5]

api:
  host: "0.0.0.0"
  port: 8001
